[package]
name = "cell-machine"
version = "0.1.0"
authors = ["Matthew K"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "^0.8.4"
macroquad = "0.3"
colour = "0.6.0"